# Generated by Django 3.2.6 on 2022-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingsubscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betforcast',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
