# Generated by Django 3.2.6 on 2022-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalsubscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptosignal',
            name='photo',
            field=models.ImageField(null=True, upload_to='signals/'),
        ),
    ]
