# Generated by Django 3.2.6 on 2022-03-25 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signalsubscription', '0002_cryptosignal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptosignal',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
